Repository Volcano-Risk-Reduction-in-Canada/Volcanic-Interpretation-Workbench, pull requests merged in 2024-06, with the labels that each got.

#38 bug fixes and new scripts
  scripts/count_processed_interferograms.py
  scripts/get_latest_coh_matrices.py
Labels: bug

#41 Add --host and --port CLI arguments
  app/dash_app.py
Labels: enhancement, Priority: Should Have

#39 Implementation of Rastertiles, removal of GeoServer
  .gitignore
  app/Data/Garibaldi/3M23/CoherenceMatrix.csv
  app/Data/LavaFork/3M41/CoherenceMatrix.csv
  app/Data/Meager/5M10/CoherenceMatrix.csv
  app/Data/Meager/5M10/bperp_all
  app/Data/Meager/5M21/CoherenceMatrix.csv
  app/Data/Meager/5M3/CoherenceMatrix.csv
  app/Data/Tseax/3M19/CoherenceMatrix.csv
  app/pages/overview.py
  app/pages/site.py
  sample_config.ini
Labels: enhancement, Priority: Must Have

#46 flake8 fixes
  app/data_utils.py
  app/pages/overview.py
Labels: bug

#55 Create docker-build.yml
  .github/workflows/docker-build.yml
Labels: enhancement, Priority: Must Have, User: Developer

#50 Bug/use environment variable
  .github/workflows/docker-build.yml
  .gitignore
  Dockerfile
  README.md
  app/dash_app.py
  app/data_utils.py
  app/global_variables.py
  app/pages/overview.py
  app/pages/site.py
  docker-compose.yml
  requirements.txt
  runDocker.sh
  sample_.env
  sample_config.ini
  scripts/calc_avg_coh.py
  scripts/create_InSAR_pair_sqs.py
  scripts/data_utils.py
  scripts/downloadEODMSData.sh
  scripts/gen_avg_coh_matrix.py
  scripts/geoserverLocalREST.sh
  scripts/geoserverREST.sh
  scripts/get_latest_baselines.py
  scripts/get_latest_coh_matrices.py
  scripts/load_updated_coherence_matrix.py
Labels: enhancement, Priority: Must Have, User: Developer
